AllCops:
  Exclude:
    - 'Gemfile'

  DisplayStyleGuide: true

  TargetRubyVersion: 3.0

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'spec/**/*'
